name: metric_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.1
  http: ^1.1.0
  logging: ^1.0.2
  hive: ^2.2.3
  json_annotation: ^4.6.0

dev_dependencies:
  lints: ^2.0.0
  test: null
  build_runner: ^2.0.0
  hive_generator: ^1.1.3
  json_serializable: ^6.0.0
